name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          run: | 
            cypress run --spec "cypress/integration/1941720031.spec.js,cypress/integration/test"
