name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          run: | 
            npx cypress run --record --spec "cypress/integration/1941720013.js"
            npx cypress run --record --spec "cypress/integration/1941720031.js"
            npx cypress run --record --spec "cypress/integration/1941720044.js"
            npx cypress run --record --spec "cypress/integration/1941720052.js"
            npx cypress run --record --spec "cypress/integration/2041723016.js"
