name: Chrome

on: push

jobs:
  chrome:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Chrome
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          run: npx cypress run --record --spec "cypress/integration/my-spec.js"
